### ISSUE TITLE
development checklist

### ISSUE THREAD

**Issue by caver456** [ncssar/kpgTools#1]
- [x] log file header - date, time, script name, script version / last modified date
- [x] consider dec handling - often it is intentionally different - maybe just remove dec from the criteria of what defines a ‘same set’ - but, should dec then be compared or not?  Example: calcord: there are four entries with that name (listed in part 1), but only three entries with all of TX/RX/Enc/Dec the same.  Remove Dec from that criteria, and all four will show up in part 2.  Then also compare dec, and it will show up as a descrepancy in part 2 - which is probably what we want.
- [x] reduce duplicate entry messages in log file - maybe a -v command line switch, or, separate the discrepancies vs the duplicate messages into different parts of the log file, or, summary at the top showing all discrepancies, then detailed log below
- [x] add a list of legal synonyms for channel names, since we may want to leave some different, so they best suit the home agency
- [x] single-channel consistency checking: dec=none or dec=enc for simplex
- [x] cross-file difference summary
- [x] cross-file winmerge / tkdiff launcher, if the files are the same model etc, and similar enough that the winmerge should be useful

Additional items to compare (based on html)

- [ ] html header (before first table) - model name, frequency, etc
- [ ] Feature Selection table
- [ ] compare number of Personal sections
- [ ] System Information table
- [ ] in each Zone, compare the tables that come before the first Channel Edit section
  - [ ] Zone/Channel Information table
  - [ ] Zone Edit table (but skip the following table of channel data; that is all compared in detail already
  - [ ] General table
  - [ ] Scan table
- [x] all tables after the last Channel Edit section - starting with 'Optional Features'
